#!/bin/bash
# Renaming script for: 08-技术指标-KDJ
# Total files: 50
# Files to rename: 50
# Generated on: 2025-11-05

cd "C:/Users/liang/GitHub/strategies/08-技术指标-KDJ"

git mv "5分钟K线KDJ指标动态响应交易策略-5-Minute-KDJ-Indicator-Dynamic-Response-Trading-Strategy.md" "001-分钟线指标动态响应交易策略-5-k-kdj-5-minute-kdj-indicator-dynamic-response-trading-strategy.md"
git mv "KDJ阳线突破买入策略KDJ-Golden-Cross-Long-Entry-Strategy.md" "002-阳线突破买入策略-kdj-kdj-golden-cross-long-entry-strategy.md"
git mv "Stochastic-Supertrend跟踪止损交易策略Stochastic-Supertrend-Tracking-Stop-Loss-Trading-Strategy.md" "003-跟踪止损交易策略-stochastic-supertrend-stochastic-supertrend-tracking-stop-loss-trading-strategy.md"
git mv "Stochastic动量突破策略Stochastic-Momentum-Breakout-Strategy.md" "004-动量突破策略-stochastic-stochastic-momentum-breakout-strategy.md"
git mv "一目均衡动力指数策略Ichimoku-Oscillator-with-Stochastic-Momentum-Index-Strategy.md" "005-一目均衡动力指数策略-ichimoku-oscillator-with-stochastic-momentum-index-strategy.md"
git mv "三重叠加随机动量策略Triple-Overlapping-Stochastic-Momentum-Strategy.md" "006-三重叠加随机动量策略-triple-overlapping-stochastic-momentum-strategy.md"
git mv "动态趋势反转与随机指标结合的自适应交易策略-Adaptive-Trading-Strategy-Combining-Dynamic-Trend-Reversal-and-Stochastic-Indicator.md" "007-动态趋势反转与随机指标结合的自适应交易策略-adaptive-trading-strategy-combining-dynamic-trend-reversal-and-stochastic-indicator.md"
git mv "动量增强型超级趋势-随机双指标交易策略-Momentum-Enhanced-SuperTrend-Stochastic-Dual-Indicator-Trading-Strategy.md" "008-动量增强型超级趋势随机双指标交易策略-momentum-enhanced-supertrend-stochastic-dual-indicator-trading-strategy.md"
git mv "动量指标与随机指标联合策略A-DMI-Stochastic-Trading-Strategy-with-Dynamic-Stop-loss.md" "009-动量指标与随机指标联合策略-a-dmi-stochastic-trading-strategy-with-dynamic-stop-loss.md"
git mv "动量趋势型SuperTrend与随机指标交叉策略-Momentum-Trend-Following-SuperTrend-and-Stochastic-Crossover-Strategy.md" "010-动量趋势型与随机指标交叉策略-supertrend-momentum-trend-following-supertrend-and-stochastic-crossover-strategy.md"
git mv "双平滑随机指数布雷瑟策略Dual-Smoothed-Stochastic-Bressert-Strategy.md" "011-双平滑随机指数布雷瑟策略-dual-smoothed-stochastic-bressert-strategy.md"
git mv "双指标滤波交易策略Stochastic-Moving-Average-Strategy-with-Double-Filters.md" "012-双指标滤波交易策略-stochastic-moving-average-strategy-with-double-filters.md"
git mv "双时间周期随机指标动量交易策略-Dual-Timeframe-Stochastic-Momentum-Trading-Strategy.md" "013-双时间周期随机指标动量交易策略-dual-timeframe-stochastic-momentum-trading-strategy.md"
git mv "双重Stochastic底部反转策略Combined-Stochastic-Oscillator-and-123-Reversal-Strategy.md" "014-双重底部反转策略-stochastic-combined-stochastic-oscillator-and-123-reversal-strategy.md"
git mv "双重随机滤波器敏锐离散分析策略Awesome-Oscillator-Double-Stochastic-Filtered-Divergence-Trading-Strategy.md" "015-双重随机滤波器敏锐离散分析策略-awesome-oscillator-double-stochastic-filtered-divergence-trading-strategy.md"
git mv "双重随机策略Dual-Stochastics-Strategy.md" "016-双重随机策略-dual-stochastics-strategy.md"
git mv "双随机动能指标筛选策略Stochastic-Momentum-Dual-Indicators-Strategy.md" "017-双随机动能指标筛选策略-stochastic-momentum-dual-indicators-strategy.md"
git mv "双随机震荡指数策略Dual-Stochastic-Oscillator-Strategy.md" "018-双随机震荡指数策略-dual-stochastic-oscillator-strategy.md"
git mv "埃勒斯-费希尔相对活力指数策略Ehlers-Fisher-Stochastic-Relative-Vigor-Index-Strategy.md" "019-埃勒斯费希尔相对活力指数策略-ehlers-fisher-stochastic-relative-vigor-index-strategy.md"
git mv "埃勒斯随机周期量化交易策略Ehlers-Stochastic-Cyber-Cycle-Strategy.md" "020-埃勒斯随机周期量化交易策略-ehlers-stochastic-cyber-cycle-strategy.md"
git mv "基于-Stochastics-Momentum-Index-的趋势追踪策略Momentum-Surfer-Strategy-Based-on-Stochastics-Momentum-Index.md" "021-基于的趋势追踪策略-stochastics-momentum-index-momentum-surfer-strategy-based-on-stochastics-momentum-index.md"
git mv "基于Stochastic-Index指标的短线交易策略Short-term-Trading-Strategy-Based-on-Stochastic-Index.md" "022-基于指标的短线交易策略-stochastic-index-short-term-trading-strategy-based-on-stochastic-index.md"
git mv "基于Stochastic指标的周期性期权交易策略Stochastic-Weekly-Options-Trading-Strategy.md" "023-基于指标的周期性期权交易策略-stochastic-stochastic-weekly-options-trading-strategy.md"
git mv "基于Stochastic指标的弹性止损短期交易策略Short-term-Trading-Strategy-Based-on-Stochastic-Indicator-with-Elastic-Stop-Loss.md" "024-基于指标的弹性止损短期交易策略-stochastic-short-term-trading-strategy-based-on-stochastic-indicator-with-elastic-stop-loss.md"
git mv "基于Stochastic指标的长短交叉策略Stochastic-Crossover-Long-and-Short-Strategy.md" "025-基于指标的长短交叉策略-stochastic-stochastic-crossover-long-and-short-strategy.md"
git mv "基于波动率指标和随机指标的多时间周期交易策略The-Multi-Period-Trading-Strategy-Based-on-Volatility-Index-and-Stochastic-Oscillator.md" "026-基于波动率指标和随机指标的多时间周期交易策略-the-multi-period-trading-strategy-based-on-volatility-index-and-stochastic-oscillator.md"
git mv "基于随机力矩指标的量化交易策略Quantitative-Trading-Strategy-Based-on-Stochastics-Momentum-Index.md" "027-基于随机力矩指标的量化交易策略-quantitative-trading-strategy-based-on-stochastics-momentum-index.md"
git mv "基于随机慢速指标的交易策略KRK-ADA-1H-Stochastic-Slow-Strategy-with-More-Entries-and-AI.md" "028-基于随机慢速指标的交易策略-krk-ada-1h-stochastic-slow-strategy-with-more-entries-and-ai.md"
git mv "基于随机指标交叉的交易策略Stochastics-Crossover-Trading-Strategy.md" "029-基于随机指标交叉的交易策略-stochastics-crossover-trading-strategy.md"
git mv "基于随机振荡指标的波动区间交易策略-Volatility-Range-Trading-Strategy-Based-on-Stochastic-Oscillator.md" "030-基于随机振荡指标的波动区间交易策略-volatility-range-trading-strategy-based-on-stochastic-oscillator.md"
git mv "基于随机转向因子和关键反转信号的组合反转策略Combination-Reversal-Strategy-Based-on-Stochastic-Turnaround-Factor-and-Key-Reversal-Signal.md" "031-基于随机转向因子和关键反转信号的组合反转策略-combination-reversal-strategy-based-on-stochastic-turnaround-factor-and-key-reversal-signal.md"
git mv "增强型动量震荡与随机背离量化交易策略-Enhanced-Momentum-Oscillator-and-Stochastic-Divergence-Quantitative-Trading-Strategy.md" "032-增强型动量震荡与随机背离量化交易策略-enhanced-momentum-oscillator-and-stochastic-divergence-quantitative-trading-strategy.md"
git mv "多参数随机震荡智能趋势交易策略-Multi-Parameter-Stochastic-Intelligent-Trend-Trading-Strategy.md" "033-多参数随机震荡智能趋势交易策略-multi-parameter-stochastic-intelligent-trend-trading-strategy.md"
git mv "多周期趋势跟踪与随机震荡优化策略-Multi-Timeframe-Trend-Following-with-Stochastic-Oscillator-Strategy.md" "034-多周期趋势跟踪与随机震荡优化策略-multi-timeframe-trend-following-with-stochastic-oscillator-strategy.md"
git mv "多指标优化型KDJ趋势交叉策略基于动态随机形态的交易系统-Multi-Indicator-Optimized-KDJ-Trend-Crossover-Strategy-Based-on-Dynamic-Stochastic-Pattern-Trading-System.md" "035-多指标优化型趋势交叉策略基于动态随机形态的交易系统-kdj-multi-indicator-optimized-kdj-trend-crossover-strategy-based-on-dynamic-stochastic-pattern-trading-system.md"
git mv "多时框随机震荡趋势跟踪交易策略-Multi-Timeframe-Stochastic-Oscillator-Trend-Following-Trading-Strategy.md" "036-多时框随机震荡趋势跟踪交易策略-multi-timeframe-stochastic-oscillator-trend-following-trading-strategy.md"
git mv "多时间周期标准偏差K线交叉策略Multi-Timeframe-Stochastic-Crossover-Strategy.md" "037-多时间周期标准偏差线交叉策略-k-multi-timeframe-stochastic-crossover-strategy.md"
git mv "多时间框架随机指标波段交易策略与动态止盈止损系统-Multi-Timeframe-Stochastic-Oscillator-Swing-Trading-Strategy-with-Dynamic-Take-Profit-and-Stop-Loss.md" "038-多时间框架随机指标波段交易策略与动态止盈止损系统-multi-timeframe-stochastic-oscillator-swing-trading-strategy-with-dynamic-take-profit-and-stop-loss.md"
git mv "多重时间框架自适应动态KDJ指标策略-Multi-Timeframe-Adaptive-Dynamic-KDJ-Indicator-Strategy.md" "039-多重时间框架自适应动态指标策略-kdj-multi-timeframe-adaptive-dynamic-kdj-indicator-strategy.md"
git mv "多重级别ZigZag百分比回撤与随机指标结合交易策略-Multi-Level-ZigZag-Percentage-Retracement-with-Stochastic-Trading-Strategy.md" "040-多重级别百分比回撤与随机指标结合交易策略-zigzag-multi-level-zigzag-percentage-retracement-with-stochastic-trading-strategy.md"
git mv "多重随机震荡策略与动量分析系统-Multi-Stochastic-Oscillation-and-Momentum-Analysis-System.md" "041-多重随机震荡策略与动量分析系统-multi-stochastic-oscillation-and-momentum-analysis-system.md"
git mv "平均随机指标交易策略Average-Stochastic-Trading-Strategy.md" "042-平均随机指标交易策略-average-stochastic-trading-strategy.md"
git mv "慢速随机指标趋势追踪策略Slow-Stochastic-Trend-Following-Strategy.md" "043-慢速随机指标趋势追踪策略-slow-stochastic-trend-following-strategy.md"
git mv "指数平滑随机指标异动策略Exponential-Smoothed-Stochastic-Oscillator-Strategy.md" "044-指数平滑随机指标异动策略-exponential-smoothed-stochastic-oscillator-strategy.md"
git mv "测试-关于使用kdj与vol量筛选可能会涨的币种.md" "045-测试关于使用与量筛选可能会涨的币种-kdj-vol.md"
git mv "纯Stochastic多头交易策略Pure-Stochastic-Long-Only-Strategy.md" "046-纯多头交易策略-stochastic-pure-stochastic-long-only-strategy.md"
git mv "随机OTT交易策略Stochastic-OTT-Trading-Strategy.md" "047-随机交易策略-ott-stochastic-ott-trading-strategy.md"
git mv "随机交叉指标动量交易策略-Stochastic-Crossover-Indicator-Momentum-Trading-Strategy.md" "048-随机交叉指标动量交易策略-stochastic-crossover-indicator-momentum-trading-strategy.md"
git mv "随机指标双轨突破策略Stochastic-Oscillator-Band-Breakout-Strategy.md" "049-随机指标双轨突破策略-stochastic-oscillator-band-breakout-strategy.md"
git mv "随机漩涡策略Stochastic-Vortex-Strategy.md" "050-随机漩涡策略-stochastic-vortex-strategy.md"

echo "Completed: 50 files renamed"
