#!/bin/bash

# Agent 5 Renaming Scripts for Trading Method Group A
# Directories: 12-高频交易, 13-网格交易, 14-套利, 15-马丁格尔

# ========================================
# Directory: 12-交易方法-高频交易 (51 files)
# ========================================
cd "C:\Users\liang\GitHub\strategies\12-交易方法-高频交易"

git mv "2014年的简易比特币高频策略机器人.md" "001-简易比特币高频做市策略-simple-bitcoin-high-frequency-market-making-strategy.md"
git mv "30分钟震荡交易策略30-Minute-Swing-Trading-Strategy.md" "002-三十分钟震荡交易策略-30-minute-swing-trading-strategy.md"
git mv "Bitcoin-Scalper-30MIN.md" "003-比特币三十分钟剥头皮策略-bitcoin-scalper-30min.md"
git mv "C期货高频套币策略OKEX-Websocket版.md" "004-期货高频套币策略okex-websocket版-futures-high-frequency-arbitrage-strategy-okex-websocket-version.md"
git mv "FVG动量短线交易策略-FVG-Momentum-Scalping-Strategy.md" "005-公允价值缺口动量短线交易策略-fvg-momentum-scalping-strategy.md"
git mv "Goblin-Town-60min-可用版.md" "006-哥布林镇六十分钟策略-goblin-town-60min-strategy.md"
git mv "HFT高频订单流因子.md" "007-高频订单流因子策略-hft-order-flow-factor-strategy.md"
git mv "Nifty50三分钟开盘价突破策略-Nifty-50-3-Minute-Opening-Range-Breakout-Strategy.md" "008-印度指数三分钟开盘价突破策略-nifty-50-3-minute-opening-range-breakout-strategy.md"
git mv "Range-Filter-Buy-and-Sell-5min-Strategy.md" "009-区间过滤五分钟买卖策略-range-filter-buy-and-sell-5min-strategy.md"
git mv "Scalping-PullBack-Tool-R1.md" "010-短线回调交易工具-scalping-pullback-tool-r1.md"
git mv "Scalping-Swing-Trading-Tool-R1-4.md" "011-短线震荡交易工具-scalping-swing-trading-tool-r1-4.md"
git mv "Simple-1m-Scalper-by-thimblemunch.md" "012-简单一分钟剥头皮策略-simple-1m-scalper-by-thimblemunch.md"
git mv "Super-Scalper.md" "013-超级剥头皮策略-super-scalper.md"
git mv "Super-Scalper-5-Min-15-Min.md" "014-超级剥头皮五至十五分钟策略-super-scalper-5-min-15-min.md"
git mv "三分钟短仓专家顾问策略3-Min-Short-Only-Expert-Advisor-Strategy.md" "015-三分钟短仓专家顾问策略-3-min-short-only-expert-advisor-strategy.md"
git mv "三行代码实现阿尔戈斯机器学习快速解读行业新闻的反指策略.md" "016-机器学习快速解读行业新闻反向指标策略-machine-learning-news-sentiment-contrarian-strategy.md"
git mv "中高频动态区间中点突破限价交易策略-Midpoint-Crossing-Dynamic-Range-Limit-Order-Trading-Strategy.md" "017-中高频动态区间中点突破限价交易策略-midpoint-crossing-dynamic-range-limit-order-trading-strategy.md"
git mv "十五分钟图表高级交易信号策略-Advanced-15-Minute-Chart-Trading-Signal-Strategy.md" "018-十五分钟图表高级交易信号策略-advanced-15-minute-chart-trading-signal-strategy.md"
git mv "单点狙击高频加仓自动反手解套算法-V12.md" "019-单点狙击高频加仓自动反手解套算法-single-point-sniper-high-frequency-position-adding-algorithm-v12.md"
git mv "坎普敦15分钟蜡烛突破策略Cape-Town-15-min-Candle-Breakout-Strategy.md" "020-坎普敦十五分钟蜡烛突破策略-cape-town-15-min-candle-breakout-strategy.md"
git mv "基于15分钟突破的高效价格通道交易策略-Efficient-Price-Channel-Trading-Strategy-Based-on-15-Minute-Breakout.md" "021-基于十五分钟突破的高效价格通道交易策略-efficient-price-channel-trading-strategy-based-on-15-minute-breakout.md"
git mv "基于BTC15分钟图表的技术交易策略-Technical-Trading-Strategy-for-BTC-15-minute-Chart.md" "022-基于比特币十五分钟图表的技术交易策略-technical-trading-strategy-for-btc-15-minute-chart.md"
git mv "基于K线形态的高频套利策略Up-Down-K-Line-Pattern-High-Frequency-Arbitrage-Strategy.md" "023-基于k线形态的高频套利策略-up-down-k-line-pattern-high-frequency-arbitrage-strategy.md"
git mv "基于K线收盘方向的高频交易突破策略-High-Frequency-Breakout-Trading-Strategy-Based-on-Candlestick-Close-Direction.md" "024-基于k线收盘方向的高频交易突破策略-high-frequency-breakout-trading-strategy-based-on-candlestick-close-direction.md"
git mv "基于三分钟K线高低点的日内突破策略-Intraday-Breakout-Strategy-Based-on-3-Minute-Candle-High-Low-Points.md" "025-基于三分钟k线高低点的日内突破策略-intraday-breakout-strategy-based-on-3-minute-candle-high-low-points.md"
git mv "基于会话突破的短线扩散交易策略Session-Breakout-Scalping-Strategy.md" "026-基于会话突破的短线扩散交易策略-session-breakout-scalping-strategy.md"
git mv "基于动态波动率的高频指数均线交叉量化策略-Dynamic-Volatility-Driven-High-Frequency-EMA-Crossover-Quantitative-Strategy.md" "027-基于动态波动率的高频指数均线交叉量化策略-dynamic-volatility-driven-high-frequency-ema-crossover-quantitative-strategy.md"
git mv "基于双重过滤的高频量化交易策略Double-Filtering-High-Frequency-Quantitative-Trading-Strategy.md" "028-基于双重过滤的高频量化交易策略-double-filtering-high-frequency-quantitative-trading-strategy.md"
git mv "基于均线交叉的高频量化交易策略Intraday-Moving-Average-Crossover-Trading-Strategy.md" "029-基于均线交叉的高频量化交易策略-intraday-moving-average-crossover-trading-strategy.md"
git mv "基于影线的反转高频交易策略Reversal-High-Frequency-Trading-Strategy-Based-on-Shadow-Line.md" "030-基于影线的反转高频交易策略-reversal-high-frequency-trading-strategy-based-on-shadow-line.md"
git mv "基于趋势过滤的快速QQE交叉策略Fast-QQE-Crossover-Trading-Strategy-Based-on-Trend-Filter.md" "031-基于趋势过滤的快速qqe交叉策略-fast-qqe-crossover-trading-strategy-based-on-trend-filter.md"
git mv "抢盘口做市策略-高频逼近型.md" "032-抢盘口做市策略高频逼近型-aggressive-market-making-high-frequency-strategy.md"
git mv "每1分钟统计各个平台间的差价by-JackConan.md" "033-每一分钟统计各平台间差价策略-1-minute-cross-platform-price-difference-statistics-strategy.md"
git mv "比特币和黄金5分钟震荡交易策略20Bitcoin-and-Gold-5-Minute-Scalping-Strategy-20.md" "034-比特币和黄金五分钟震荡交易策略-bitcoin-and-gold-5-minute-scalping-strategy-20.md"
git mv "波浪买卖反转5分钟时间框架策略Wave-Buying-and-Selling-Reversal-5-Minutes-Timeframe-Strategy.md" "035-波浪买卖反转五分钟时间框架策略-wave-buying-and-selling-reversal-5-minutes-timeframe-strategy.md"
git mv "短期极限空头策略Extreme-Short-term-Scalping-Strategy.md" "036-短期极限空头策略-extreme-short-term-scalping-strategy.md"
git mv "穿越时空的莫非指标策略Money-Flow-Index-5-Minute-Strategy-Across-Time-and-Space.md" "037-穿越时空的资金流指标五分钟策略-money-flow-index-5-minute-strategy-across-time-and-space.md"
git mv "自适应分形网格波段交易策略与波动率阈值优化系统-Adaptive-Fractal-Grid-Scalping-Strategy-with-Volatility-Threshold-Optimization-System.md" "038-自适应分形网格波段交易策略与波动率阈值优化系统-adaptive-fractal-grid-scalping-strategy-with-volatility-threshold-optimization-system.md"
git mv "诺罗波动通道scalping策略Noros-Price-Channel-Scalping-Strategy.md" "039-诺罗波动通道短线策略-noros-price-channel-scalping-strategy.md"
git mv "金森一分钟震荡策略Gem-Forest-One-Minute-Scalping-Strategy.md" "040-金森一分钟震荡策略-gem-forest-one-minute-scalping-strategy.md"
git mv "高频交易策略之-Penny-Jump.md" "041-高频交易策略之便士跳跃-high-frequency-trading-strategy-penny-jump.md"
git mv "高频动态开盘区间突破交易策略-Dynamic-Opening-Range-Breakout-High-Frequency-Trading-Strategy.md" "042-高频动态开盘区间突破交易策略-dynamic-opening-range-breakout-high-frequency-trading-strategy.md"
git mv "高频收割机一号.md" "043-高频收割机一号策略-high-frequency-harvester-no1-strategy.md"
git mv "高频混合技术分析量化策略-High-Frequency-Hybrid-Technical-Analysis-Quantitative-Strategy.md" "044-高频混合技术分析量化策略-high-frequency-hybrid-technical-analysis-quantitative-strategy.md"
git mv "高频翻转百分比追踪动量策略-High-Frequency-Flip-Percentage-Tracking-Momentum-Strategy.md" "045-高频翻转百分比追踪动量策略-high-frequency-flip-percentage-tracking-momentum-strategy.md"
git mv "高频跨期套利策略.md" "046-高频跨期套利策略-high-frequency-calendar-spread-arbitrage-strategy.md"
git mv "高频量化交易中的趋势匹配与退出优化策略-High-Frequency-Quantitative-Trading-Strategy-with-Trend-Matching-and-Exit-Optimization.md" "047-高频量化交易中的趋势匹配与退出优化策略-high-frequency-quantitative-trading-strategy-with-trend-matching-and-exit-optimization.md"
git mv "高频量化会话交易策略基于突破信号的自适应动态仓位管理系统-High-Frequency-Quantitative-Session-Trading-Strategy-Adaptive-Dynamic-Position-Management-System-Based-on-Breakout-Signals.md" "048-高频量化会话交易策略基于突破信号的自适应动态仓位管理系统-high-frequency-quantitative-session-trading-strategy-adaptive-dynamic-position-management-system-based-on-breakout-signals.md"
git mv "黄金快速突破策略Breakout-Scalper-Catching-Trend-Changes-Quickly.md" "049-黄金快速突破策略-breakout-scalper-catching-trend-changes-quickly.md"
git mv "黄金森林1分钟突破策略Gem-Forest-1-Minute-Breakout-Strategy.md" "050-黄金森林一分钟突破策略-gem-forest-1-minute-breakout-strategy.md"
git mv "黄金短线交易策略-XAUUSD-Scalper-1m-XAUUSD-1-Minute-Scalping-Strategy.md" "051-黄金短线交易策略-xauusd-scalper-1m-xauusd-1-minute-scalping-strategy.md"

# ========================================
# Directory: 13-交易方法-网格交易 (51 files)
# ========================================
cd "C:\Users\liang\GitHub\strategies\13-交易方法-网格交易"

git mv "50行网格策略教学.md" "001-五十行网格策略教学-50-line-grid-strategy-tutorial.md"
git mv "bybit反向合约动态网格特异网格.md" "002-bybit反向合约动态网格特异网格-bybit-inverse-contract-dynamic-grid-strategy.md"
git mv "grid.md" "003-基础网格策略-basic-grid-strategy.md"
git mv "Python版简单网格策略教学.md" "004-python版简单网格策略教学-python-simple-grid-strategy-tutorial.md"
git mv "SpotGridStra.md" "005-现货网格策略-spot-grid-strategy.md"
git mv "U本位网格振幅筛选.md" "006-u本位网格振幅筛选策略-usdt-based-grid-amplitude-filtering-strategy.md"
git mv "Wavetrend-大幅指标超跌反弹网格交易策略-Wavetrend-Large-Amplitude-Oversold-Rebound-Grid-Trading-Strategy.md" "007-波浪趋势大幅指标超跌反弹网格交易策略-wavetrend-large-amplitude-oversold-rebound-grid-trading-strategy.md"
git mv "主动自适应量化网格交易策略Self-adaptive-Quant-Grid-Trading-Strategy.md" "008-主动自适应量化网格交易策略-self-adaptive-quant-grid-trading-strategy.md"
git mv "动态均线网格交易策略Grid-Strategy-with-Moving-Average-Lines.md" "009-动态均线网格交易策略-grid-strategy-with-moving-average-lines.md"
git mv "动态网格交易策略Assassins-Grid-B-A-Dynamic-Grid-Trading-Strategy.md" "010-动态网格交易策略刺客版-assassins-grid-b-a-dynamic-grid-trading-strategy.md"
git mv "动态网格交易策略Dynamic-Grid-Trading-Strategy.md" "011-动态网格交易策略-dynamic-grid-trading-strategy.md"
git mv "动态网格交易管理策略Dynamic-Grid-Trading-Management-Strategy.md" "012-动态网格交易管理策略-dynamic-grid-trading-management-strategy.md"
git mv "动态网格趋势追踪量化交易策略Dynamic-Grid-Trend-Following-Quantitative-Trading-Strategy.md" "013-动态网格趋势追踪量化交易策略-dynamic-grid-trend-following-quantitative-trading-strategy.md"
git mv "单边网格.md" "014-单边网格策略-unilateral-grid-strategy.md"
git mv "双向合约网格交易v102.md" "015-双向合约网格交易v102-bidirectional-contract-grid-trading-v102.md"
git mv "双向网格K线追踪交易策略Grid-Trading-Strategy-Based-on-Real-time-K-line-Tracking.md" "016-双向网格k线追踪交易策略-grid-trading-strategy-based-on-real-time-k-line-tracking.md"
git mv "固定网格交易策略Fixed-Grid-Trading-Strategy.md" "017-固定网格交易策略-fixed-grid-trading-strategy.md"
git mv "基于下跌幅度与目标利润的多头网格策略-Long-Grid-Strategy-Based-on-Drawdown-and-Target-Profit.md" "018-基于下跌幅度与目标利润的多头网格策略-long-grid-strategy-based-on-drawdown-and-target-profit.md"
git mv "基于动态网格交易策略Dynamic-Grid-Trading-Strategy.md" "019-基于动态网格交易策略-based-dynamic-grid-trading-strategy.md"
git mv "基于均线系统的网格交易策略Grid-Trading-Strategy-Based-on-Moving-Average-System.md" "020-基于均线系统的网格交易策略-grid-trading-strategy-based-on-moving-average-system.md"
git mv "基于多空自适应动态网格策略A-Long-Short-Adaptive-Dynamic-Grid-Strategy-Based.md" "021-基于多空自适应动态网格策略-long-short-adaptive-dynamic-grid-strategy-based.md"
git mv "基于网格交易的自适应加密货币套利策略Adaptive-Cryptocurrency-Grid-Trading-Strategy-Based-on-Arbitrage.md" "022-基于网格交易的自适应加密货币套利策略-adaptive-cryptocurrency-grid-trading-strategy-based-on-arbitrage.md"
git mv "基于网格的多头-Martingale-动态加仓网格交易策略Grid-based-Long-Martingale-Dynamic-Position-Grid-Trading-Strategy.md" "023-基于网格的多头马丁格尔动态加仓网格交易策略-grid-based-long-martingale-dynamic-position-grid-trading-strategy.md"
git mv "基于连续K线动态网格自适应均线动态止损策略-Continuous-Candle-Based-Dynamic-Grid-Adaptive-Moving-Average-with-Dynamic-Stop-Loss-Strategy.md" "024-基于连续k线动态网格自适应均线动态止损策略-continuous-candle-based-dynamic-grid-adaptive-moving-average-with-dynamic-stop-loss-strategy.md"
git mv "基于量化交易平台的自适应网格交易策略Adaptive-Grid-Trading-Strategy-Based-on-Quantitative-Trading-Platform.md" "025-基于量化交易平台的自适应网格交易策略-adaptive-grid-trading-strategy-based-on-quantitative-trading-platform.md"
git mv "基于马丁格尔理论的网格式加仓策略模型-Grid-based-Position-Accumulation-Strategy-Based-on-Martingale-Theory.md" "026-基于马丁格尔理论的网格式加仓策略模型-grid-based-position-accumulation-strategy-based-on-martingale-theory.md"
git mv "基础网格交易策略.md" "027-基础网格交易策略-basic-grid-trading-strategy.md"
git mv "子辰量化无限网格交易策略.md" "028-子辰量化无限网格交易策略-zichen-quant-infinite-grid-trading-strategy.md"
git mv "子辰量化香农网格交易策略.md" "029-子辰量化香农网格交易策略-zichen-quant-shannon-grid-trading-strategy.md"
git mv "币安合约网格-002v.md" "030-币安合约网格002v-binance-contract-grid-002v.md"
git mv "币安合约网格-基础版本-001.md" "031-币安合约网格基础版本001-binance-contract-grid-basic-version-001.md"
git mv "暴雪网格-724小时交易机器人每日更新实盘效果.md" "032-暴雪网格724小时交易机器人-blizzard-grid-724-hour-trading-bot.md"
git mv "海洋理论网格交易策略Ocean-Theory-Grid-Trading-Strategy.md" "033-海洋理论网格交易策略-ocean-theory-grid-trading-strategy.md"
git mv "简单网格测试.md" "034-简单网格测试策略-simple-grid-test-strategy.md"
git mv "简易等差合约网格.md" "035-简易等差合约网格策略-simple-arithmetic-contract-grid-strategy.md"
git mv "网格交易风险对冲策略Grid-Trading-Risk-Hedging-Strategy.md" "036-网格交易风险对冲策略-grid-trading-risk-hedging-strategy.md"
git mv "网格变形策略之单边网格.md" "037-网格变形策略之单边网格-grid-variant-strategy-unilateral-grid.md"
git mv "网格变形策略之单边网格-OK期货.md" "038-网格变形策略之单边网格ok期货-grid-variant-strategy-unilateral-grid-ok-futures.md"
git mv "网格变形策略之单边网格-注释.md" "039-网格变形策略之单边网格注释版-grid-variant-strategy-unilateral-grid-commented.md"
git mv "网格合约.md" "040-网格合约策略-grid-contract-strategy.md"
git mv "网格挂单加马丁倍数递增.md" "041-网格挂单加马丁倍数递增策略-grid-limit-order-with-martingale-multiplier-increment-strategy.md"
git mv "网格管理工具.md" "042-网格管理工具-grid-management-tool.md"
git mv "网格美元成本平均策略Grid-Dollar-Cost-Averaging-Strategy.md" "043-网格美元成本平均策略-grid-dollar-cost-averaging-strategy.md"
git mv "自适应成本均值动态网格策略-基于DCA与马丁格尔原理的高级量化交易系统-Adaptive-Cost-Average-Dynamic-Grid-Strategy-Advanced-Quantitative-Trading-System-Based-on-DCA-and-Martingale-Principles.md" "044-自适应成本均值动态网格策略基于dca与马丁格尔原理的高级量化交易系统-adaptive-cost-average-dynamic-grid-strategy-advanced-quantitative-trading-system-based-on-dca-and-martingale-principles.md"
git mv "自适应智能网格交易策略Adaptive-Intelligent-Grid-Trading-Strategy.md" "045-自适应智能网格交易策略-adaptive-intelligent-grid-trading-strategy.md"
git mv "自适应网格交易策略与动态调整机制-Adaptive-Grid-Trading-Strategy-with-Dynamic-Adjustment-Mechanism.md" "046-自适应网格交易策略与动态调整机制-adaptive-grid-trading-strategy-with-dynamic-adjustment-mechanism.md"
git mv "趋势跟随可变仓位网格策略-Trend-Following-Variable-Position-Grid-Strategy.md" "047-趋势跟随可变仓位网格策略-trend-following-variable-position-grid-strategy.md"
git mv "趋势追踪网格策略Trend-Following-Grid-Strategy.md" "048-趋势追踪网格策略-trend-following-grid-strategy.md"
git mv "趋势马丁网格ver100策略仅供学习参考.md" "049-趋势马丁网格ver100策略-trend-martingale-grid-ver100-strategy.md"
git mv "震荡盈利波段Grid策略Profit-Grid-Strategy-With-Oscillation.md" "050-震荡盈利波段网格策略-profit-grid-strategy-with-oscillation.md"
git mv "麦语言网格策略.md" "051-麦语言网格策略-my-language-grid-strategy.md"

# ========================================
# Directory: 14-交易方法-套利 (45 files)
# ========================================
cd "C:\Users\liang\GitHub\strategies\14-交易方法-套利"

git mv "50行多平台对冲策略教学.md" "001-五十行多平台对冲策略教学-50-line-multi-platform-hedging-strategy-tutorial.md"
git mv "60行三角对冲策略教学.md" "002-六十行三角对冲策略教学-60-line-triangular-hedging-strategy-tutorial.md"
git mv "Bit-Maker-30-套利-智能学习-USDT-本位-Binance-单平台-Arbitrage-USDT-Standard.md" "003-比特制造者30套利智能学习usdt本位币安单平台-bit-maker-30-arbitrage-intelligent-learning-usdt-standard-binance-single-platform.md"
git mv "Deribit期权Delta动态对冲策略教学.md" "004-deribit期权delta动态对冲策略教学-deribit-option-delta-dynamic-hedging-strategy-tutorial.md"
git mv "Hedge_BTC-ETH-Demo.md" "005-比特币以太坊对冲演示-hedge-btc-eth-demo.md"
git mv "HUSD-USD稳定币套利.md" "006-husd-usd稳定币套利策略-husd-usd-stablecoin-arbitrage-strategy.md"
git mv "OKEX期现对冲.md" "007-okex期现对冲策略-okex-spot-futures-hedging-strategy.md"
git mv "OKEx跨期对冲策略.md" "008-okex跨期对冲策略-okex-calendar-spread-hedging-strategy.md"
git mv "rest-版OKEX跨期对冲策略教学.md" "009-rest版okex跨期对冲策略教学-rest-version-okex-calendar-spread-hedging-strategy-tutorial.md"
git mv "websocket-版OKEX跨期对冲策略教学.md" "010-websocket版okex跨期对冲策略教学-websocket-version-okex-calendar-spread-hedging-strategy-tutorial.md"
git mv "三角套利-基础版.md" "011-三角套利基础版-triangular-arbitrage-basic-version.md"
git mv "三角套利策略体验版.md" "012-三角套利策略体验版-triangular-arbitrage-strategy-trial-version.md"
git mv "三角套利赚取小币种盘口价差.md" "013-三角套利赚取小币种盘口价差策略-triangular-arbitrage-altcoin-orderbook-spread-strategy.md"
git mv "不同计价币的现货对冲策略-Ver11.md" "014-不同计价币的现货对冲策略ver11-different-quote-currency-spot-hedging-strategy-ver11.md"
git mv "不同计价币的现货对冲策略教学.md" "015-不同计价币的现货对冲策略教学-different-quote-currency-spot-hedging-strategy-tutorial.md"
git mv "动量套利策略回测分析Momentum-Arbitrage-Strategy-Backtest-Analysis.md" "016-动量套利策略回测分析-momentum-arbitrage-strategy-backtest-analysis.md"
git mv "动量跟踪自适应统计套利策略Momentum-Tracking-Adaptive-Statistical-Arbitrage-Strategy.md" "017-动量跟踪自适应统计套利策略-momentum-tracking-adaptive-statistical-arbitrage-strategy.md"
git mv "双均线套利策略Dual-Moving-Average-Arbitrage-Strategy.md" "018-双均线套利策略-dual-moving-average-arbitrage-strategy.md"
git mv "双平台对冲js版本two-platforms-hedging-JS.md" "019-双平台对冲js版本-two-platforms-hedging-js-version.md"
git mv "双平台对冲平衡策略.md" "020-双平台对冲平衡策略-two-platforms-hedging-balance-strategy.md"
git mv "双平台对冲-练习用-求交流求指点.md" "021-双平台对冲练习用-two-platforms-hedging-practice-version.md"
git mv "合约对冲_下单多线程版本.md" "022-合约对冲下单多线程版本-contract-hedging-multi-threaded-order-placement-version.md"
git mv "基于两个市场价格关系的套利交易策略-Price-Relationship-based-Arbitrage-Trading-Strategy-Between-Two-Markets.md" "023-基于两个市场价格关系的套利交易策略-price-relationship-based-arbitrage-trading-strategy-between-two-markets.md"
git mv "基于双重反转套利策略Dual-Reversal-Arbitrage-Strategy.md" "024-基于双重反转套利策略-dual-reversal-arbitrage-strategy.md"
git mv "基于适应性正则化移动平均线的跨市场套利策略Adaptive-Regularized-Moving-Average-Cross-Market-Arbitrage-Strategy.md" "025-基于适应性正则化移动平均线的跨市场套利策略-adaptive-regularized-moving-average-cross-market-arbitrage-strategy.md"
git mv "多品种期现对冲-手动版.md" "026-多品种期现对冲手动版-multi-product-spot-futures-hedging-manual-version.md"
git mv "多品种期货跨期对冲策略.md" "027-多品种期货跨期对冲策略-multi-product-futures-calendar-spread-hedging-strategy.md"
git mv "多平台对冲稳定套利.md" "028-多平台对冲稳定套利策略-multi-platform-hedging-stable-arbitrage-strategy.md"
git mv "套利下单.md" "029-套利下单工具-arbitrage-order-placement-tool.md"
git mv "套利图表.md" "030-套利图表工具-arbitrage-chart-tool.md"
git mv "对冲27收益率统计系统-支持多组账号统计.md" "031-对冲27收益率统计系统支持多组账号统计-hedging-27-yield-statistics-system-multi-account-support.md"
git mv "对冲震荡反转策略Hedging-Oscillation-Reversal-Strategy.md" "032-对冲震荡反转策略-hedging-oscillation-reversal-strategy.md"
git mv "币安OKX永续自动对冲.md" "033-币安okx永续自动对冲策略-binance-okx-perpetual-auto-hedging-strategy.md"
git mv "币安合约蝶式套利千团大战策略3.md" "034-币安合约蝶式套利千团大战策略3-binance-contract-butterfly-arbitrage-battle-strategy-3.md"
git mv "币安永续双账户单币种对冲YNRUN.md" "035-币安永续双账户单币种对冲ynrun-binance-perpetual-dual-account-single-currency-hedging-ynrun.md"
git mv "币安永续多币种对冲策略做多超跌做空超涨-张总python版.md" "036-币安永续多币种对冲策略做多超跌做空超涨-binance-perpetual-multi-currency-hedging-strategy-long-oversold-short-overbought.md"
git mv "币安永续多币种对冲策略做空或做多山寨币指数4月10日改进Bug需要更新.md" "037-币安永续多币种对冲策略做空或做多山寨币指数-binance-perpetual-multi-currency-hedging-strategy-short-or-long-altcoin-index.md"
git mv "币安永续多币种对冲策略原版做多超跌做空超涨4月13日最新止损模块.md" "038-币安永续多币种对冲策略原版做多超跌做空超涨-binance-perpetual-multi-currency-hedging-strategy-original-long-oversold-short-overbought.md"
git mv "指数对冲修罗场-001.md" "039-指数对冲修罗场001-index-hedging-battlefield-001.md"
git mv "期货一键对冲插件Hedge-on-two-contracts.md" "040-期货一键对冲插件-hedge-on-two-contracts-plugin.md"
git mv "比特币现货阶梯差价对冲.md" "041-比特币现货阶梯差价对冲策略-bitcoin-spot-ladder-spread-hedging-strategy.md"
git mv "简单的做市对冲功能.md" "042-简单的做市对冲功能-simple-market-making-hedging-function.md"
git mv "跨平台套利新手测试.md" "043-跨平台套利新手测试-cross-platform-arbitrage-beginner-test.md"
git mv "跨趋势跟随套利181策略Valeria-181-Robot-Strategy-Improved-24.md" "044-跨趋势跟随套利181策略-cross-trend-following-arbitrage-181-strategy-valeria-181-robot-strategy-improved-24.md"
git mv "长线对冲策略Long-Term-Hedging-Strategy.md" "045-长线对冲策略-long-term-hedging-strategy.md"

# ========================================
# Directory: 15-交易方法-马丁格尔 (28 files)
# ========================================
cd "C:\Users\liang\GitHub\strategies\15-交易方法-马丁格尔"

git mv "30行赌徒策略.md" "001-三十行赌徒策略-30-line-gambler-strategy.md"
git mv "30行赌徒策略-做空.md" "002-三十行赌徒策略做空版-30-line-gambler-strategy-short-version.md"
git mv "CTA策略之商品期货简易马丁格尔.md" "003-cta策略之商品期货简易马丁格尔-cta-strategy-commodity-futures-simple-martingale.md"
git mv "Paul-The-Gambler-Lévy.md" "004-保罗赌徒莱维策略-paul-the-gambler-levy-strategy.md"
git mv "VWMA-EMA均线交叉马丁格尔策略渐进式增仓优化量化交易系统-VWMA-EMA-Crossover-Martingale-Strategy-Progressive-Position-Scaling-Optimized-Quantitative-Trading-System.md" "005-vwma-ema均线交叉马丁格尔策略渐进式增仓优化量化交易系统-vwma-ema-crossover-martingale-strategy-progressive-position-scaling-optimized-quantitative-trading-system.md"
git mv "WR-突破马丁.md" "006-威廉指标突破马丁策略-wr-breakout-martingale-strategy.md"
git mv "八阶蜡烛模式序列马丁格尔策略-Eight-Candle-Pattern-Sequence-Martingale-Strategy.md" "007-八阶蜡烛模式序列马丁格尔策略-eight-candle-pattern-sequence-martingale-strategy.md"
git mv "分享-赌徒策略-马丁策略.md" "008-分享赌徒策略马丁策略-shared-gambler-strategy-martingale-strategy.md"
git mv "动态均线回撤马丁策略Dynamic-Moving-Average-Retracement-Martin-Strategy.md" "009-动态均线回撤马丁策略-dynamic-moving-average-retracement-martin-strategy.md"
git mv "币安多产品趋势马丁与逆势马丁策略分享.md" "010-币安多产品趋势马丁与逆势马丁策略分享-binance-multi-product-trend-martingale-and-counter-trend-martingale-strategy-sharing.md"
git mv "拓宽均线区间的马丁格尔止损炒股策略Martingale-Strategy-with-Expanded-Moving-Average-Range-for-Stock-Trading.md" "011-拓宽均线区间的马丁格尔止损炒股策略-martingale-strategy-with-expanded-moving-average-range-for-stock-trading.md"
git mv "数字货币期货类马丁策略.md" "012-数字货币期货类马丁策略-cryptocurrency-futures-martingale-strategy.md"
git mv "智能间隔倍投策略出售版.md" "013-智能间隔倍投策略出售版-intelligent-interval-martingale-strategy-for-sale-version.md"
git mv "暴力马丁适合eth和btc-Copy.md" "014-暴力马丁适合eth和btc-aggressive-martingale-suitable-for-eth-and-btc.md"
git mv "杠杆化马丁格尔期货交易策略Leveraged-Martingale-Futures-Trading-Strategy.md" "015-杠杆化马丁格尔期货交易策略-leveraged-martingale-futures-trading-strategy.md"
git mv "条件开仓马丁.md" "016-条件开仓马丁策略-conditional-entry-martingale-strategy.md"
git mv "测试-关于马丁长期效果.md" "017-测试关于马丁长期效果-test-martingale-long-term-effectiveness.md"
git mv "简单马丁格尔btc合约修改加仓倍率.md" "018-简单马丁格尔btc合约修改加仓倍率-simple-martingale-btc-contract-modified-position-multiplier.md"
git mv "简单马丁格尔合约倍率加强版.md" "019-简单马丁格尔合约倍率加强版-simple-martingale-contract-multiplier-enhanced-version.md"
git mv "简单马丁格尔多空交易策略.md" "020-简单马丁格尔多空交易策略-simple-martingale-long-short-trading-strategy.md"
git mv "简单马丁格尔多空加仓倍率修改.md" "021-简单马丁格尔多空加仓倍率修改-simple-martingale-long-short-position-multiplier-modification.md"
git mv "自适应动量马丁格尔交易系统-Adaptive-Momentum-Martingale-Trading-System.md" "022-自适应动量马丁格尔交易系统-adaptive-momentum-martingale-trading-system.md"
git mv "随机数马丁格尔策略.md" "023-随机数马丁格尔策略-random-number-martingale-strategy.md"
git mv "马丁变种原始版.md" "024-马丁变种原始版-martingale-variant-original-version.md"
git mv "马丁格尔打印收益图表.md" "025-马丁格尔打印收益图表-martingale-print-profit-chart.md"
git mv "马丁格尔测试.md" "026-马丁格尔测试-martingale-test.md"
git mv "马丁策略-V001.md" "027-马丁策略v001-martingale-strategy-v001.md"
git mv "魔改马丁双向持仓.md" "028-魔改马丁双向持仓策略-modified-martingale-bidirectional-position-strategy.md"

echo "Renaming scripts generated successfully!"
echo "Total files to rename: 175"
echo "  - 12-交易方法-高频交易: 51 files"
echo "  - 13-交易方法-网格交易: 51 files"
echo "  - 14-交易方法-套利: 45 files"
echo "  - 15-交易方法-马丁格尔: 28 files"
