#!/bin/bash
# Renaming script for: 07-技术指标-CCI
# Total files: 55
# Files to rename: 55
# Generated on: 2025-11-05

cd "C:/Users/liang/GitHub/strategies/07-技术指标-CCI"

git mv "4小时CCI反转策略4-Hour-CCI-Reversal-Strategy.md" "001-小时反转策略-4-cci-4-hour-cci-reversal-strategy.md"
git mv "CCI-MTF-ObOs.md" "002-cci-mtf-obos.md"
git mv "CCI动量背离趋势交易策略CCI-Momentum-Divergence-Trend-Trading-Strategy.md" "003-动量背离趋势交易策略-cci-cci-momentum-divergence-trend-trading-strategy.md"
git mv "CCI强势突破策略CCI-Strong-Breakthrough-Strategy.md" "004-强势突破策略-cci-cci-strong-breakthrough-strategy.md"
git mv "CCI零点反转交易策略CCI-Zero-Cross-Trading-Strategy.md" "005-零点反转交易策略-cci-cci-zero-cross-trading-strategy.md"
git mv "Fibonacci-Extension-and-Retracement-Channel-Breakout-Strategy-斐波那契延展回撤通道突破策略.md" "006-斐波那契延展回撤通道突破策略-fibonacci-extension-and-retracement-channel-breakout-strategy.md"
git mv "Fibonacci-Progression-With-Breaks.md" "007-fibonacci-progression-with-breaks.md"
git mv "Fibonacci-Timing-Pattern.md" "008-fibonacci-timing-pattern.md"
git mv "动态CCI支撑阻力策略Dynamic-CCI-Support-and-Resistance-Strategy.md" "009-动态支撑阻力策略-cci-dynamic-cci-support-and-resistance-strategy.md"
git mv "动态CCI突破策略DCCI-Breakout-Strategy.md" "010-动态突破策略-cci-dcci-breakout-strategy.md"
git mv "动态斐波那契回撤交易策略-Dynamic-Fibonacci-Retracement-Trading-Strategy.md" "011-动态斐波那契回撤交易策略-dynamic-fibonacci-retracement-trading-strategy.md"
git mv "动态波浪趋势与斐波那契综合量化交易策略-Dynamic-WaveTrend-and-Fibonacci-Integrated-Quantitative-Trading-Strategy.md" "012-动态波浪趋势与斐波那契综合量化交易策略-dynamic-wavetrend-and-fibonacci-integrated-quantitative-trading-strategy.md"
git mv "动量突破纤维套利策略Incremental-Order-Size-Fibonacci-Retracement-Trend-Following-Strategy.md" "013-动量突破纤维套利策略-incremental-order-size-fibonacci-retracement-trend-following-strategy.md"
git mv "动量追踪CCI策略Momentum-Tracking-CCI-Strategy.md" "014-动量追踪策略-cci-momentum-tracking-cci-strategy.md"
git mv "双CCI滤波momentum爆发交易策略Dual-CCI-Filtered-Momentum-Explosion-Trading-Strategy.md" "015-双滤波爆发交易策略-cci-momentum-dual-cci-filtered-momentum-explosion-trading-strategy.md"
git mv "双cci量化策略Dual-CCI-Quantitative-Strategy.md" "016-双量化策略-cci-dual-cci-quantitative-strategy.md"
git mv "基于CCI周期性区间交易策略.md" "017-基于周期性区间交易策略-cci.md"
git mv "基于CCI指标的趋势跟踪策略CCI-Dual-Timeframe-Trend-Following-Strategy.md" "018-基于指标的趋势跟踪策略-cci-cci-dual-timeframe-trend-following-strategy.md"
git mv "基于CCI指标的长线交易策略CCI-Long-Only-Strategy.md" "019-基于指标的长线交易策略-cci-cci-long-only-strategy.md"
git mv "基于CCI零位的趋势追踪策略CCI-Zero-Crossing-Trend-Following-Strategy.md" "020-基于零位的趋势追踪策略-cci-cci-zero-crossing-trend-following-strategy.md"
git mv "基于Fibonacci水平的日内高低价突破Breakthrough-of-Daily-High-low-Price-Based-on-Fibonacci-Levels.md" "021-基于水平的日内高低价突破-fibonacci-breakthrough-of-daily-high-low-price-based-on-fibonacci-levels.md"
git mv "基于OBV和CCI指标的趋势追踪策略OBV-and-CCI-Indicators-Based-Trend-Following-Strategy.md" "022-基于和指标的趋势追踪策略-obv-cci-obv-and-cci-indicators-based-trend-following-strategy.md"
git mv "基于Stochastic指标和CCI指标的趋势跟踪策略Trend-Following-Strategy-Based-on-Stochastic-and-CCI.md" "023-基于指标和指标的趋势跟踪策略-stochastic-cci-trend-following-strategy-based-on-stochastic-and-cci.md"
git mv "基于TSI和HMACCI指标的双边套利策略Trend-Surfing-Hedging-Strategy-Based-on-TSI-and-HMACCI-Indicators.md" "024-基于和指标的双边套利策略-tsi-hmacci-trend-surfing-hedging-strategy-based-on-tsi-and-hmacci-indicators.md"
git mv "基于华尔街捕鼠光环指标的加密货币看涨看跌策略Correlation-based-Bullish-Bearish-Crypto-Trading-Strategy-Based-on-Wall-Street-CCI-Index.md" "025-基于华尔街捕鼠光环指标的加密货币看涨看跌策略-correlation-based-bullish-bearish-crypto-trading-strategy-based-on-wall-street-cci-index.md"
git mv "基于多时间周期赫斯特指数与斐波那契回撤的动态趋势交易策略Multi-Timeframe-Hurst-Exponent-and-Fibonacci-Retracement-Dynamic-Trend-Trading-Strategy.md" "026-基于多时间周期赫斯特指数与斐波那契回撤的动态趋势交易策略-multi-timeframe-hurst-exponent-and-fibonacci-retracement-dynamic-trend-trading-strategy.md"
git mv "基于斐波那契07水平的趋势突破量化交易策略-Quantitative-Trading-Strategy-Based-on-Fibonacci-07-Level-Trend-Breakthrough.md" "027-基于斐波那契水平的趋势突破量化交易策略-07-quantitative-trading-strategy-based-on-fibonacci-07-level-trend-breakthrough.md"
git mv "基于斐波那契回撤水平的多重条件趋势跟踪量化交易策略-Multi-Condition-Trend-Following-Quantitative-Trading-Strategy-Based-on-Fibonacci-Retracement-Levels.md" "028-基于斐波那契回撤水平的多重条件趋势跟踪量化交易策略-multi-condition-trend-following-quantitative-trading-strategy-based-on-fibonacci-retracement-levels.md"
git mv "基于斐波那契回撤的自适应多级别交易策略-Adaptive-Multi-Level-Trading-Strategy-Based-on-Fibonacci-Retracement.md" "029-基于斐波那契回撤的自适应多级别交易策略-adaptive-multi-level-trading-strategy-based-on-fibonacci-retracement.md"
git mv "基于斐波那契回撤的自适应趋势跟踪策略-Adaptive-Trend-Following-Strategy-Based-on-Fibonacci-Retracement.md" "030-基于斐波那契回撤的自适应趋势跟踪策略-adaptive-trend-following-strategy-based-on-fibonacci-retracement.md"
git mv "基于斐波那契回撤的量化交易策略Fibonacci-Retracement-Quantitative-Trading-Strategy.md" "031-基于斐波那契回撤的量化交易策略-fibonacci-retracement-quantitative-trading-strategy.md"
git mv "基于斐波那契回调和成交量增量的交易策略-Delta-Volume-with-Fibonacci-Levels-Trading-Strategy.md" "032-基于斐波那契回调和成交量增量的交易策略-delta-volume-with-fibonacci-levels-trading-strategy.md"
git mv "基于斐波那契通道的K线反转策略Fibonacci-Channel-Based-Candlestick-Reversal-Trading-Strategy.md" "033-基于斐波那契通道的线反转策略-k-fibonacci-channel-based-candlestick-reversal-trading-strategy.md"
git mv "基于纤程指标的移动止损限价策略Fibonacci-Retracement-Dynamic-Stop-Loss-Strategy.md" "034-基于纤程指标的移动止损限价策略-fibonacci-retracement-dynamic-stop-loss-strategy.md"
git mv "基于肯特纳通道和CCI指标的趋势过滤量化策略Trend-Filter-Quantitative-Strategy-Based-on-Keltner-Channels-and-CCI-Indicator.md" "035-基于肯特纳通道和指标的趋势过滤量化策略-cci-trend-filter-quantitative-strategy-based-on-keltner-channels-and-cci-indicator.md"
git mv "基于超级趋势和CCI指标的多时间框架交易策略Best-Supertrend-CCI-Multi-Timeframe-Trading-Strategy.md" "036-基于超级趋势和指标的多时间框架交易策略-cci-best-supertrend-cci-multi-timeframe-trading-strategy.md"
git mv "基于超趋势和CCI策略的短线交易Supertrend-and-CCI-Scalping-Strategy.md" "037-基于超趋势和策略的短线交易-cci-supertrend-and-cci-scalping-strategy.md"
git mv "多周期斐波那契回撤结合趋势突破交易策略-Multi-Timeframe-Fibonacci-Retracement-with-Trend-Breakout-Trading-Strategy.md" "038-多周期斐波那契回撤结合趋势突破交易策略-multi-timeframe-fibonacci-retracement-with-trend-breakout-trading-strategy.md"
git mv "多指标交叉趋势跟踪策略结合斐波那契回调及止盈止损优化系统-Multi-Indicator-Crossover-Trend-Following-Strategy-with-Fibonacci-Retracement-and-Stop-Loss-Take-Profit-Optimization-System.md" "039-多指标交叉趋势跟踪策略结合斐波那契回调及止盈止损优化系统-multi-indicator-crossover-trend-following-strategy-with-fibonacci-retracement-and-stop-loss-take-profit-optimization-system.md"
git mv "多维枢轴点交易策略与动态斐波那契指标系统-Multi-Dimensional-Pivot-Point-Trading-System-with-Dynamic-Fibonacci-Indicators.md" "040-多维枢轴点交易策略与动态斐波那契指标系统-multi-dimensional-pivot-point-trading-system-with-dynamic-fibonacci-indicators.md"
git mv "斐波那契回撤与延展多重指标量化交易策略-Fibonacci-Retracement-and-Extension-Multi-Indicator-Quantitative-Trading-Strategy.md" "041-斐波那契回撤与延展多重指标量化交易策略-fibonacci-retracement-and-extension-multi-indicator-quantitative-trading-strategy.md"
git mv "斐波那契模式统计分析策略-Fibonacci-Pattern-Statistical-Analysis-Strategy.md" "042-斐波那契模式统计分析策略-fibonacci-pattern-statistical-analysis-strategy.md"
git mv "斐波那契趋势反转策略-Fibonacci-Trend-Reversal-Strategy.md" "043-斐波那契趋势反转策略-fibonacci-trend-reversal-strategy.md"
git mv "斐波那契黄金分割回撤买入策略-Fibonacci-Golden-Ratio-Retracement-Buying-Strategy.md" "044-斐波那契黄金分割回撤买入策略-fibonacci-golden-ratio-retracement-buying-strategy.md"
git mv "斐波那契黄金和谐突破策略-Fibonacci-Golden-Harmony-Breakout-Strategy.md" "045-斐波那契黄金和谐突破策略-fibonacci-golden-harmony-breakout-strategy.md"
git mv "望远适应-CCI-底部捕捉商品交易策略Extended-Adaptive-CCI-Bottom-Fishing-Trading-Strategy-for-Commodities.md" "046-望远适应底部捕捉商品交易策略-cci-extended-adaptive-cci-bottom-fishing-trading-strategy-for-commodities.md"
git mv "自适应多时间框架斐波纳契波段交易策略Adaptive-Multi-Timeframe-Fibonacci-Retracement-Trading-Strategy.md" "047-自适应多时间框架斐波纳契波段交易策略-adaptive-multi-timeframe-fibonacci-retracement-trading-strategy.md"
git mv "超趋势和CCI策略的短线交易Supertrend-and-CCI-Scalping-Strategy.md" "048-超趋势和策略的短线交易-cci-supertrend-and-cci-scalping-strategy.md"
git mv "量化交易精准多空策略Fibonacci-Zone-DCA-Strategy.md" "049-量化交易精准多空策略-fibonacci-zone-dca-strategy.md"
git mv "高级动态Fibonacci回撤趋势量化交易策略-Advanced-Dynamic-Fibonacci-Retracement-Trend-Quantitative-Trading-Strategy.md" "050-高级动态回撤趋势量化交易策略-fibonacci-advanced-dynamic-fibonacci-retracement-trend-quantitative-trading-strategy.md"
git mv "高级斐波那契回撤趋势追踪与反转交易策略-Advanced-Fibonacci-Retracement-Trend-Following-and-Reversal-Trading-Strategy.md" "051-高级斐波那契回撤趋势追踪与反转交易策略-advanced-fibonacci-retracement-trend-following-and-reversal-trading-strategy.md"
git mv "高级斐波那契回调与成交量加权价格行为交易策略-Advanced-Fibonacci-Retracement-and-Volume-Weighted-Price-Action-Trading-Strategy.md" "052-高级斐波那契回调与成交量加权价格行为交易策略-advanced-fibonacci-retracement-and-volume-weighted-price-action-trading-strategy.md"
git mv "高级时间框架Fibonacci回撤与高低点条件突破交易系统-Advanced-Timeframe-Fibonacci-Retracement-with-High-Low-Breakout-Trading-System.md" "053-高级时间框架回撤与高低点条件突破交易系统-fibonacci-advanced-timeframe-fibonacci-retracement-with-high-low-breakout-trading-system.md"
git mv "黄金分割波段震荡策略Fibonacci-Band-Oscillation-Strategy.md" "054-黄金分割波段震荡策略-fibonacci-band-oscillation-strategy.md"
git mv "黄金通道反转策略Fibonacci-Retracement-Reversal-Strategy.md" "055-黄金通道反转策略-fibonacci-retracement-reversal-strategy.md"

echo "Completed: 55 files renamed"
