#!/bin/bash
# Master Renaming Script - Executes all 6 directory renaming operations
# Generated by Agent 7
# Date: 2025-11-05

echo "=========================================="
echo "Master Renaming Script for All Directories"
echo "Total: 795 files across 6 directories"
echo "=========================================="
echo ""

# Function to execute script and report results
execute_script() {
    local script_name=$1
    local dir_name=$2
    local file_count=$3
    
    echo "----------------------------------------"
    echo "Processing: $dir_name"
    echo "Files: $file_count"
    echo "Script: $script_name"
    echo "----------------------------------------"
    
    if [ -f "$script_name" ]; then
        bash "$script_name"
        if [ $? -eq 0 ]; then
            echo "✓ SUCCESS: $dir_name completed"
        else
            echo "✗ ERROR: $dir_name failed"
            return 1
        fi
    else
        echo "✗ ERROR: Script not found - $script_name"
        return 1
    fi
    echo ""
}

# Navigate to scripts directory
cd "C:\Users\liang\GitHub\strategies"

# Execute all renaming scripts
execute_script "rename_bitcoin.sh" "21-资产类型-比特币 (Bitcoin)" "22"
execute_script "rename_gold.sh" "22-资产类型-黄金 (Gold)" "14"
execute_script "rename_ethereum.sh" "23-资产类型-以太坊 (Ethereum)" "3"
execute_script "rename_teaching.sh" "24-教学文档 (Teaching Documents)" "23"
execute_script "rename_api_tools.sh" "25-API工具 (API Tools)" "116"
execute_script "rename_other_strategies.sh" "26-其他策略 (Other Strategies)" "617"

echo "=========================================="
echo "Master Renaming Complete!"
echo "Total files processed: 795"
echo "=========================================="
